Added setupvpn.sh, cloud-bastion.ovpn and changed README.md
Otus-DevOps-2022-05/enboyko_infra pull request #3
Opened 2022-06-24 17:19 UTC by enboyko

Добрый день, Владимир!

Не проходят 2 проверки, хотя у меня работает VPN. Скажите, пожалуйста, могут ли они быть связаны со следующим:

моя домашняя основная рабочая машина - на Windows: на ней я работаю с Git. В YC я создал дополнительную ВМ под названием **myubuntu** c Ubuntu, на которой делал домашнее задание - подключался по ssh, настроил VPN и прочее. Возможно, скрипт проверяет попытку подключения по VPN с моей Windows-машины, и у него это, конечно, не получается?

В Slack я Вам поскидываю разные скрины моих настроек, и что у меня всё работает. Здесь не знаю, как(

Я пока все мои три машины в YC не буду останавливать, чтобы можно было разобраться в происходящем.

2022-06-25 09:04 UTC, mrgreyves requested changes
Здравствуйте!)
То что вы работает с Windows это кажется нормальным
Оформлена дз у вас корректно
Кажется что у вас проблемы с подключение
Может быть вы ошиблись с каким нибудь пинкодом для подключения когда создавали pritunl сервер?
Самый простой способ проверить локально, это поставить open vpn клиент, импортировать в него конфиг сервера и попробовать подключиться
Давайте я пока что отправлю дз в доработку
Если будут доп вопросы, вы можете оставлять их в комментариях к пуллреквестам =)

2022-06-26 21:33 UTC, enboyko commented
Доброй ночи, Владимир! :-)))
Я разобрался: неправильно вводил данные для подключения) Видимо, мне нужно сделать новый пуллреквест, т.к. в самом коде (в ветке) я ничего не менял. Подскажите, пожалуйста, есть ли в подобном случае (когда изменений в коде нет) возможность как-то перезапустить тесты?))

2022-06-26 21:35 UTC, enboyko commented
Хотяя, вряд ли это возможно, т.к. тесты запускаются при коммитах, да?)

2022-06-26 21:54 UTC, enboyko commented
Урааа!!! Проверки прошли!!! :-)

2022-06-26 23:37 UTC, enboyko commented
Владимир, теперь можно у Вас получить промокод (или денюжку - не помню, как правильно говорить) для последующей работы с Yandex.Cloud?))

2022-06-27 15:40 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь апрув
Постарайтесь побыстрее помержить эту дз
ЗЫ: промокоды будуту выдавать сегодня =)

2022-06-27 16:35 UTC, enboyko commented
Добрый день!)
Спасибо, Владимир!!!=-)

2022-06-27 16:35 UTC, merged