Terraform 2
Otus-DevOps-2022-05/enboyko_infra pull request #8
Opened 2022-07-14 23:46 UTC by enboyko

# Выполнено ДЗ №7

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
1. Создал ресурсы сети yandex_vpc_network и подсети yandex_vpc_network для конфигурирования будущих ВМ
2. Настроил неявную зависимость одного ресурса от другого
3. Пересоздал ресурсы с учетом неявной зависимости.
4. Создал два новых шаблона для Packer'а : db.json и app.json
5. С помощью шаблона db.json собрал образ VM, содержащий установленную MongoDB
6. С помощью шаблона app.json собрал образ VM с установленными Ruby
7. Разбил конфиг main.tf на 3 конфига: app.tf, db.tf и vpc.tf. Разбил остальную конфигурацию по файлам  и создал ресурсы (инстансы)
8. Видоизменил конфигурацию, разбив на модули db и app. Создал ресурсы
9. Добавил модули prod и stage. Создал ресурсы
10. Отформатировал все конфигурационные файлы, использовав команду terraform fmt
11. Подменил для Git настоящие файлы terraform.tfvars файлами terraform.tfvars.example c вымышленными значениями. Также подменил key.json

## Как запустить проект:
 - Выполнить команду для создания ресурса:
    `terraform apply`

## Как проверить работоспособность:
 - Перейти по ссылкам с IP созданных инстансов с указанием порта **9292**

## PR checklist
 - [x] Выставил "Labels" **terraform-2** и **terraform** домашнего задания

2022-07-14 23:50 UTC, enboyko commented
Владимир, добрый день! :-))

Я усиленно борюсь с тестами)))
Задания со звездочками я не делал. Автотесты требуют наличия файла **terraform/storage-bucket.tf** из дополнительного задания. Однако, даже когда я его фиктивно создал, всё равно дальше проверки не проходят, т.к. появляются новые условия.

Можно ли в таком случае просто пренебречь тестами или же как-то относительно легко внести небольшие корректировки?)

2022-07-15 14:13 UTC, mrgreyves requested changes
Здравствуйте!)
На самом деле, вам стоит внести совсем минимальные правки
Добавить просто определение переменных
Либо из определить, либо добавить default значение
Приключение на 10 минут
Давайте наведем красоту =)

2022-07-15 14:19 UTC, enboyko commented
> Здравствуйте!) На самом деле, вам стоит внести совсем минимальные правки Добавить просто определение переменных Либо из определить, либо добавить default значение Приключение на 10 минут Давайте наведем красоту =)

Добрый день, Владимир!))
Спасибо! ^_^

2022-07-17 20:35 UTC, enboyko commented
Владимир, добрый день! :-))

Сделал, как Вы мне сказали, и тесты прошли успешно! :relaxed:

2022-07-18 13:43 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2022-07-18 13:44 UTC, merged